# Change these first
owner: oblien # Your GitHub organization or username, where this repository lives
repo: status # The name of this repository

sites:
  - name: Oblien API
    url: https://api.oblien.com/health
  - name: Workspace Gateway
    url: https://workspace.oblien.com/health
  - name: SSH Gateway
    url: https://ssh.oblien.com/health
  - name: Edge Network
    url: https://edge.oblien.com/health

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.oblien.com
  # baseUrl: /your-repo-name
  logoUrl: https://oblien.com/ico/android-chrome-512x512.png
  name: Oblien Status
  introTitle: "**Oblien** is your real-time uptime monitor and status page, powered entirely by GitHub Actions."
  introMessage: "This status page shows **real-time uptime and incidents** for all Oblien services. No extra server required — just GitHub Actions, Issues, and Pages. [**See our repo**](https://github.com/oblien/status)."
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/oblien/status


# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
