owner: oblien
repo: status

sites:
  - name: Oblien API
    url: https://api.oblien.com/health
  - name: Workspace Gateway
    url: https://workspace.oblien.com/health
  - name: SSH Gateway
    url: https://ssh.oblien.com/health
  - name: Edge Network
    url: https://edge.oblien.com/health

status-website:
  cname: status.oblien.com
  logoUrl: https://oblien.com/ico/android-chrome-512x512.png
  name: Oblien Status
